### ISSUE TITLE
itslive_ui._get_temporal_coverage

### ISSUE THREAD

**Issue by whyjz** [nasa-jpl/its_live_production#1]
Hi,

At line 116-117 of `itslive.py`:
```
start_date = datetime.strptime(file_components[3], "%Y%m%d").date()
end_date = datetime.strptime(file_components[4], "%Y%m%d").date()
```
Here is a sample file name from the query URL: `LC08_L1TP_082233_20180627_20180704_01_T1_X_LC08_L1TP_082233_20180611_20180615_01_T1_G0240V01_P094.nc`. Maybe I am wrong, but it looks that the `start_date` should be `file_components[11]` and the `end_date` should be `file_components[3]`?

**Comment by betolink** [comment]
You're right, this is a bug. 

There is a new repo coming out this week that will fix this bug and enhance how we build data cubes on the fly.

**Comment by whyjz** [comment]
Great thanks a lot!
