### ISSUE TITLE
ITS_LIVE next steps

### ISSUE THREAD

**Issue by alex-s-gardner** [nasa-jpl/its_live_production#12]
- [x]  fix filenames for existing V2 S2 image-pair data

- [x]  fix all existing V2 image-pair data
- Sentinel-1 acquisition attributes (**acquisition_img1/2** attribute should be **acquisition_date_img1/2**)
- add missing sensor_img1="MSI" and sensor_img2="MSI" attributes for Sentinel-2's img_pair_info
- fix all references to   https://its-live-data.jpl.nasa.gov.s3.amazonaws.com
- recompute date_center and date_dt attributes of img_pair_info to use time stamp of acquisition_date_img[12]
- remove vp, vxp, vyp, vp_error layers from S1 layers
- recompute S1, S2 and L8 stable shift
 
- [x] update datacube code
- fix all references to   https://its-live-data.jpl.nasa.gov.s3.amazonaws.com
- add cube name and url of data cubes need to be added as global   attributes
- add proj_polygon (x, y)
- add geo_polygon (lon, lat)

- [x] finish composites code

 
- [x] develop mosaic code

**Comment by mliukis** [comment]
@alex-s-gardner Do you need to remove **vp_error** along with **vp, vxp, vyp** layers from S1 layers?

**Comment by alex-s-gardner** [comment]
@mliukis Yes, good point. We need to remove vp_error as well...
