### ISSUE TITLE
Sentinel-2 granules are missing sensor_img1 and sensor_img2 in img_pair_info

### ISSUE THREAD

**Issue by mliukis** [nasa-jpl/its_live_production#6]
```
Variable “img_pair_info”
In file “S2B_20190827_L1C_X_S2A_20190901_L1C_G0120V02_P099.nc”
String img_pair_info;
  :mission_img1 = "S";
  :satellite_img1 = "2B";
  :correction_level_img1 = "L1C";
  :acquisition_date_img1 = "20190827T15:13:15.";
  :time_standard_img1 = "UTC";
  :mission_img2 = "S";
  :satellite_img2 = "2A";
  :correction_level_img2 = "L1C";
  :acquisition_date_img2 = "20190901T15:13:11.";
  :time_standard_img2 = "UTC";
  :date_dt = 4.999953703703704; // double
  :date_center = "20190830T03:13:13.";
  :latitude = 69.76; // double
  :longitude = -46.95; // double
  :roi_valid_percentage = 99.4; // double
```

Per @alex-s-gardner, "there is only one sensor on the S2 satellites so it is safe to use satellite_img1/2... but we should add sensor_img1/2 attributes for consistency"

**Comment by jhkennedy** [comment]
@alex-s-gardner for Senintel-2, do you want, for example, `sensor_img1="2A"` (exactly the same as `satellite_img1`) or `sensor_img1="A"`?

**Comment by jhkennedy** [comment]
@alex-s-gardner or maybe `MSI` always? (`sensor_img{1,2}` for Sentinel-1, for example, is `C`)

**Comment by alex-s-gardner** [comment]
@jhkennedy  I say we follow the same convention as Sentinel-1 and use MSI

**Comment by mliukis** [comment]
@alex-s-gardner @jhkennedy Could you, please, clarify for the given example above do I set missing attributes to:

```
sensor_img1 = "B";
sensor_img1 = "A";

```
?

**Comment by jhkennedy** [comment]
@mliukis 
```
sensor_img1 = "MSI";
sensor_img2 = "MSI";
```
for sentinel-2
