### ISSUE TITLE
Replace all references to https://its-live-data.jpl.nasa.gov.s3.amazonaws.com with https://its-live-data.s3.amazonaws.com

### ISSUE THREAD

**Issue by mliukis** [nasa-jpl/its_live_production#7]
Since we are migrating to new s3://its-live-data bucket, need to replace all references pointing to the old bucket https://its-live-data.jpl.nasa.gov.s3.amazonaws.com.

Current occurrences:

* In all granules: 
    autoRIFT_parameter_file = "http://its-live-data.jpl.nasa.gov.s3.amazonaws.com/autorift_parameters/v001/autorift_landice_0120m.shp";

**Comment by jhkennedy** [comment]
@mliukis for sentinel-2 granules that have already been processed, you'll have:
```
autoRIFT_parameter_file = "http://its-live-data-eu.jpl.nasa.gov.s3.amazonaws.com/autorift_parameters/v001/autorift_landice_0120m.shp";
```
(note the `-eu`) as we have a copy in Europe for processing that dataset. 

For anything newly, you shouldn't have to worry about it -- we've ensured it on our end.
