### ISSUE TITLE
remove all projected (vp, vxp, vyp) layers from S1 netcdfs and commnet out in datacub script

### ISSUE THREAD

**Issue by alex-s-gardner** [nasa-jpl/its_live_production#8]
Yang and I discussed at length the S1 projected velocities and decided that we will not include them in the V2 release of the data as they require more thought. Therefore we need to remove these layers from existing S1 granules

**Comment by mliukis** [comment]
@alex-s-gardner Could you, please, confirm that I need to remove vp, vxp, vyp and vp_error all together from the V2 datacubes as well.

**Comment by mliukis** [comment]
Done
